language: R

# use containers; runs faster
sudo: false

cache: packages

warnings_are_errors: false

branches:
  only:
    - master

os:
  - linux

notifications:
  email:
    on_success: change
    on_failure: change

# linting
r_github_packages:
  - jimhester/lintr

# after_success:
#   - R CMD INSTALL $PKG_TARBALL
#   - Rscript -e 'lintr::lint_package()'

# Lint
script:
  - ./travis-linter.sh
